### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by maartenbreddels** [jtpio/ipylab#110]
@jtpio pretty nice project!

```python
from ipylab import JupyterFrontEnd, Panel, SplitPanel
from ipywidgets import IntSlider, Layout

app = JupyterFrontEnd()
panel = Panel()
slider = IntSlider()
panel.children = [slider]
app.shell.add(panel, 'main', { 'mode': 'split-right' })
```

gives in the js console:
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'id')
    at ShellModel._add (shell.js:44:1)
    at async ShellModel._onMessage (shell.js:89:1)
```

**Comment by maartenbreddels** [comment]
seems to work ok with ipywidgets 8.

**Comment by maartenbreddels** [comment]
Yes, binder picks up ipywidgets8.
Btw, if you kept using pWidget (see https://github.com/jupyter-widgets/ipywidgets/pull/3358/files ) it would be backward compatible.
But, I think we should make ipywidgets 7 forward compatible, and introduce a similar alias, what do you think?

**Comment by jtpio** [comment]
> kept using pWidget

This would also be fine I guess. The full update to ipywidgets 8 was mostly for simplicity, if folks would like to use ipywidgets 7 as well we could indeed allow it.

Would you like to open a PR?

**Comment by maartenbreddels** [comment]
> I think we should make ipywidgets 7 forward compatible, and introduce a similar alias, what do you think?

I think I'll try this one instead, make a patch release for ipywidgets 7 so it works with ipywidgets 8 "only" extensions
