### ISSUE TITLE
Support of notebooks in VS Code?

### ISSUE THREAD

**Issue by kolibril13** [jtpio/ipylab#138]
Would it be possible to use ipylab in VS Code notebooks?
Currently, it's failing
<img width="1510" alt="image" src="https://github.com/jtpio/ipylab/assets/44469195/ce7ac808-6dae-485e-9a52-a3a58ee47956">

similar report to
https://github.com/jtpio/ipylab/issues/114

**Comment by jtpio** [comment]
`ipylab` is based on JupyterLab, and VS Code does not seem to be using any part of JupyterLab for rendering notebooks (as far as a I know, except `@jupyterlab/services`).

So this very likely never going to be supported in this repo :)

**Comment by kolibril13** [comment]
That sounds reasonable!
VS Code has its own API to handle notebook operations:
<img width="506" alt="image" src="https://github.com/jtpio/ipylab/assets/44469195/24a0275b-3a8a-415f-8d39-08362a5af85b">
So in theory there could be a package build ontop of ipylab that checks for the platform and then calls these functions accordingly, but I think it's probably not worth the effort to make such a package.

**Comment by jtpio** [comment]
> there could be a package build ontop of ipylab

Or rather have a package similar to `ipylab`, but using the VS Code API instead. It might be possible to reuse some Python parts of the `ipylab` package, but not sure it would be worth it.
