### ISSUE TITLE
Update to JupyterLab 3.0

### ISSUE THREAD

**Issue by jtpio** [jtpio/ipylab#50]
It should be possible to update to lab 3 now that `jupyterlab_widgets` is available (pip and conda): https://pypi.org/project/jupyterlab-widgets/1.0.0a5/

**Comment by dsblank** [comment]
Jupyterlab 3.0 has been released: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.0.0

**Comment by jtpio** [comment]
Yes, it should be possible to update https://github.com/jtpio/ipylab/pull/51 to using the latest packages, merge it and publish.

Although some widgets will not work yet as they also need to be released with a version compatible with JupyterLab 3.0
