### ISSUE TITLE
Handle restore

### ISSUE THREAD

**Issue by jtpio** [jtpio/ipylab#8]
At the moment the panels are not restored on page refresh.

![not-restored](https://user-images.githubusercontent.com/591645/69014107-11144f00-0987-11ea-8589-2e174736b325.gif)

We could transparently use the `LayoutRestorer` to transparently restore these panels that are added to the `shell`.

**Comment by jtpio** [comment]
Maybe we could use a similar approach as @saulshanabrook did in https://github.com/Quansight-Labs/jupyter-widgets-takeover, instead of relying on the widget's `pWidget`.

**Comment by saulshanabrook** [comment]
I spoke too soon, unfortunately... 

Issue is we don't save the arguments to `restorer.restore(tracker, options)` anywhere so we have no way of re-restoring widgets later :(

**Comment by jtpio** [comment]
It sounds like it should be doable, but would maybe require writing a custom widget manager though.

**Comment by saulshanabrook** [comment]
I got this working with my widgets factory... it's a bit zany though: https://github.com/Quansight-Labs/jupyter-widgets-takeover/blob/a0b2af7245e420297784eb9a4338b8f6e2c8747a/src/workspace.tsx#L60-L90

**Comment by jtpio** [comment]
But it looks functional :) 

I guess it would even make sense to be able to remove the chrome in core lab as well.

**Comment by jtpio** [comment]
Ah I see you posted in https://github.com/jupyterlab/jupyterlab/issues/2031 :+1:

**Comment by saulshanabrook** [comment]
Yeah it's functional haha after many tears...

**Comment by dsblank** [comment]
I think this can be closed, now?

**Comment by jtpio** [comment]
Thanks @dsblank. Yes there is now basic support for this using the widget restoring process.

The next steps could be looking into more advanced layouts like in https://github.com/jtpio/ipylab/issues/48, and be able to restore the layout even if the widgets don't exist on the Python side yet (recreating them from a notebook path).
